export const restaurantsWords = [ 
    "Lonesome Dove",
    "Bobby’s",
    "Melting",
    "Pot",
    "Daytime",
    "Place",
    "Easy",
    "Eats",
    "Macro",
    "Bites",
    "Grubber",
    "Hub",
    "Cheerful",
    "Rhino",
    "Home",
    "Cooking",
    "Experience",
    "Fare",
    "Feed",
    "Golden",
    "Palace",
    "Soups & Snacks",
    "Quick",
    "Bite",
    "Fast",
    "&",
    "Friendly",
    "Big",
    "Bites",
    "Blind",
    "Pig",
    "Eatable",
    "Eatery",
    "Goodies",
    "Lard",
    "Boy",
    "Many",
    "Foods",
    "Me",
    "Likey",
    "Wonton",
    "Express",
    "Great",
    "Burger",
    "Awesome",
    "Burger",
    "Amazing",
    "Sauce",
    "Asian",
    "Express",
    "Fearless",
    "Wander",
    "Crate",
    "Express",
    "Smothered",
    "In",
    "Love",
    "Sweet",
    "Delectable",
    "Appetizing",
    "As",
    "Heck",
    "Appetizing",
    "Bird",
    "Scrumptious",
    "Temptations",
    "Smile N’ Delight",
    "Choice",
    "Foods",
    "Dainty",
    "Dog",
    "Hungry",
    "Dog",
    "Heavenly",
    "Creations",
    "Food For Thought",
    "Food In My Tummy",
    "Tum Tum Express",
    "Lil Johnny’s",
    "Bill’s Burgers",
]